- hosts: all
  become: 'yes'
  vars:
    user:
    packages:
      - vim
      - wget
      - curl
      - htop
      - apache2
  tasks:
    - name: Change password for default user
      user:
        name:  "pi"
        password:  " secret | password_hash('sha512')"
        state: present
    - name: Ensure a list of packages installed
      apt:
        name:  "{{ packages }}"
        state: present
    - name: share file
      copy: 
        src: /var/www/html/index.html
        dest: /var/www/html/index.html
    - name: All done!
      debug:
        msg: Packages have been successfully installed
    - name: add php  support for apache
      apt:
        name:  libapache2-mod-php
        state: latest

